import type { Metadata } from 'next'
import { Libre_Caslon_Display, Inter } from 'next/font/google'
import './globals.css'

const libreCaslonDisplay = Libre_Caslon_Display({ 
  weight: '400',
  subsets: ['latin'],
  variable: "--font-libre",
});

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${libreCaslonDisplay.variable} ${inter.variable}`}>
      <body>{children}</body>
    </html>
  )
}
