security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login_check
      stateless: true
      json_login:
        check_path: /api/login_check
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

    admin:
      pattern: ^/admin
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: admin_login
        check_path: admin_login
      logout:
        path: admin_logout

  access_control:
    - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/api/password/create, roles: PUBLIC_ACCESS }
    - { path: ^/api/password/validate-token, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
